databases:
  - name: oshisupport_db
    databaseName: oshisupport_db
    user: oshisupport
    region: singapore

services:
  - type: web
    name: oshisupport
    env: ruby
    region: singapore
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: <%= ENV['DATABASE_URL'] %>
        fromDatabase:
          name: oshisupport_db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false